language: python
dist: bionic
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
# install package + test dependencies
install:
  - pip install ".[test]" .
# run test
script:
  - pytest --cov-report term --cov==levenshtein tests/
# submit coverage
after_success:
  - codecov

